### ISSUE TITLE
todo aug 3

### ISSUE THREAD

**Issue by abnDK** [abnDK/personal-budget-2#30]
- [x] Finish add transaction on /transactions
 
- [x] clean up code with sections and comments

- [ ] sketch out budget component
